---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  roles_path: 'roles'

platforms:
  - name: ubuntu-14.04
    driver:
      box: joelhandwell/ubuntu_trusty64_vbguest

suites:
  - name: default
    run_list:
      - recipe[w_common::default]
      - role[w_tomcat_role]
    attributes:
